### ISSUE TITLE
[Request] Protocol Encryption

### ISSUE THREAD

**Issue by zero77** [webtorrent/webtorrent#1331] opened 2018-03-10 15:59 UTC
Can you please add support for protocol encryption and enable it by default, because to my knowledge all popular torrent clients have this.

Thanks

**Comment by feross** [comment] 2018-03-22 23:58
Good idea. Duplicate of https://github.com/webtorrent/webtorrent/issues/69

**Closed by feross** 2018-03-22 23:58 UTC
