### ISSUE TITLE
Client.add() throwing "cannot add duplicate" for .torrent that's never been added

### ISSUE THREAD

**Issue by 000magic** [webtorrent/webtorrent#2088] opened 2021-05-29 17:54 UTC
**What version of this package are you using?**
Latest

**What operating system, Node.js, and npm version?**
Windows 10 x64
Npm 6.14.12
Node 14.16.1

**What happened?**
I'm unable to add torrents using Client.add() as it throws
`client Error: Cannot add duplicate torrent` on every HTTP or magnet url being added.

**What did you expect to happen?**
The torrent is added.

**Are you willing to submit a pull request to fix this bug?**
Yes if I found the solution

**Comment by 000magic** [comment] 2021-05-29 17:54
I felt like I should add, `client.torrents` returns an empty array.

**Comment by alxhotel** [comment] 2021-05-29 19:16
Hi @000magic,

Thanks for opening an issue!

Can you provide a code snippet to reproduce this bug?

**Comment by 000magic** [comment] 2021-05-29 22:15
`this.magnet = "magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent";`
...
```
this.client.add(this.magnet, (t) => { // Error thrown here
  t.on("infohash", () => {
    console.log("torrent", "infohash");
  });
  t.on("metadata", () => {
    console.log("torrent", "metadata");
  });
  t.on("ready", () => {
    console.log("torrent", "ready");
  });
  t.on("warning", (warn) => {
    console.warn("torrent", warn);
  });
  t.on("error", (err) => {
    console.error("torrent", err);
  });
  t.on("done", () => {
    console.log("torrent", "done");
  });

  this.torrent = t;

  // Filter files by those with supported file extensions
  var f = t.files.filter((f) =>
    ["mp4", "mkv", "avi", "m4v"].some((ext) =>
      f.name.endsWith("." + ext)
    )
  );

  var selectedFile = f[0];
});
```

**Comment by alxhotel** [comment] 2021-05-31 20:45
Hi @000magic,

Thanks!

I have used your code in a codepen and it doesn't seem to throw any errors: https://codepen.io/alxhotel/pen/qBrparP

**Comment by wangguang2112** [comment] 2021-06-08 05:20
I put client into vue data ,then I get the same error!

**Comment by 000magic** [comment] 2021-06-10 07:44
> 
> 
> Thanks!
> 
> I have used your code in a codepen and it doesn't seem to throw any errors: https://codepen.io/alxhotel/pen/qBrparP
> 
> Can you check it out ?

I can't reproduce it in that codepen. I believe it has something to do with Vue. I'll keep trying.

**Comment by alxhotel** [comment] 2021-06-10 10:20
@wangguang2112 @000magic thanks for the answers!

It looks like Vue is re-running a part of the code that you are not expecting.

Since the bug is not in webtorrent, I'm closing this issue for now.

**Closed by alxhotel** 2021-06-10 10:20 UTC
Labels: needs reproduction
