### ISSUE TITLE
`deselect` method doesn't work when downloading

### ISSUE THREAD

**Issue by lx1412** [webtorrent/webtorrent#1948] opened 2020-11-02 10:03 UTC
**What version of this package are you using?**
On Windows: 0.103.4
On Mac: 0.109.2

**What operating system, Node.js, and npm version?**
Windows 10, Node v12.4.0
MacOs Mojave Version 10.14.6, Node v10.17.0

**What happened?**
I just want to download the second file of a torrent, but it seems that `webtorrent` downloaded other files for me.
I referred some codes of [https://github.com/webtorrent/webtorrent/issues/164#issuecomment-248395202](url) but it still doesn't work.
Here's my code. It's simple so that you can reproduce the result.
Appreciate for any help.
```
const WebTorrent = require('webtorrent');
const path = require('path')
const client = new WebTorrent();
client.on('error', console.dir)

const onMetaData = (torrent) => {
    torrent.files.forEach(file => file.deselect());
    torrent.deselect(0, torrent.pieces.length - 1, false);
    for (let i = 0; i < torrent.files.length; i++) {
        const file = torrent.files[i]
        if (i === 1) { // select the 2nd file
            file.select()
        } else {
            file.deselect()
        }
    }
};

let torrent = client.add('https://webtorrent.io/torrents/wired-cd.torrent', { path: path.join(__dirname, 'webtorrent') }, onMetaData);
```

**What did you expect to happen?**
Just download the second file.

**Are you willing to submit a pull request to fix this bug?**

**Comment by feross** [comment] 2020-11-11 03:10
Duplicate of https://github.com/webtorrent/webtorrent/issues/164

**Closed by feross** 2020-11-11 03:10 UTC
