### ISSUE TITLE
Update Flatpak version

### ISSUE THREAD

**Issue by sojusnik** [webtorrent/webtorrent#2792] opened 2024-05-23 14:14 UTC
The [Flatpak version](https://flathub.org/apps/io.webtorrent.WebTorrent) is not up-to-date. Would be great if it could be updated.

**Comment by SilentBot1** [comment] 2024-06-13 21:35
Hi @sojusnik,

This issue appears to relate to the [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) application/repo and is a duplicate of the issue https://github.com/webtorrent/webtorrent-desktop/issues/2272.

Due to this, I'm going to close this issue and ask for any further discussion/questions to take place in the issue linked above.

**Closed by SilentBot1** 2024-06-13 21:35 UTC
