### ISSUE TITLE
Using 2 torrents hangs

### ISSUE THREAD

**Issue by nkavian** [webtorrent/webtorrent#2003] opened 2021-02-14 20:47 UTC
**What version of this package are you using?**

webtorrent-hybrid: 4.0.3

**What operating system, Node.js, and npm version?**

mac: 10.14.6
node: 12.18.3
npm: 6.14.6
electron: 11.2.3

**What happened?**

Create 2 torrents using `create-torrent`. Load both torrents into WebTorrent-Desktop. Use the default [electron-quick-start](https://github.com/electron/electron-quick-start) and add the two torrents using magnet links. Run `npm install`, `npm start`, and observe that the electron application will soon hang and display a beach ball.

Note: if you only use 1 torrent instead of 2, it never hangs.
Note: when using 1 torrent, sometimes it never finds the torrent, and WebTorrent-Desktop has to be restarted.

**What did you expect to happen?**

Expected the application not to hang.

**Are you willing to submit a pull request to fix this bug?**

Not knowledgable enough about how to debug webtorrent code, but here is a branch to easily run the above mentioned scenario

https://github.com/nkavian/electron-quick-start/tree/webtorrent-hang

https://github.com/electron/electron-quick-start/compare/master...nkavian:webtorrent-hang

**Comment by nkavian** [comment] 2021-02-15 03:12
Using only 1 torrent and invoking pause or resume on it also triggers a hang. I'll wait till this original issue is addressed before making a new issue for pause/resume. I suspect it may be related.

**Comment by alxhotel** [comment] 2021-05-31 17:39
Hi @nkavian,

Thanks for the feedback and for sharing the code!

I'm sorry, I can't reproduce the hanging you are describing. The electron app seems to work fine for me. Even calling the pause or resume function does not make the app hang.

Maybe is related to your machine? I've used an Ubuntu with 8GB of RAM.

I'm closing this issue, but feel free to open it again if you find more info regarding the reproduction of the bug or the cause of it.

**Closed by alxhotel** 2021-05-31 17:39 UTC

**Comment by nkavian** [comment] 2021-05-31 19:20
Well, try using a Mac. It's been pretty consistent for me over the years that it happens on a Mac.
