### ISSUE TITLE
Add freature to bind webtorrent to a VPN

### ISSUE THREAD

**Issue by mangonebula** [webtorrent/webtorrent#2599] opened 2023-06-19 12:54 UTC
**What version of this package are you using?**
Version 0.24.0 (0.108.6)

**What problem do you want to solve?**
Keep my ip from being leaked when the VPN is not connected to avoid legal action

**What do you think is the correct solution to this problem?**
Add a feature to bind webtorrent to a VPN so that it will not make any transfers when the VPN is not connected

**Are you willing to submit a pull request to implement this change?**
No, I don't know how to

**Comment by ThaUnknown** [comment] 2023-06-19 13:09
duplicate of https://github.com/webtorrent/webtorrent/issues/2158

**Closed by ThaUnknown** 2023-06-19 13:09 UTC
