### ISSUE TITLE
Bring torrents to the browser (chrome extension)

### ISSUE THREAD

**Issue by aqwsez** [webtorrent/webtorrent#443] opened 2015-09-26 18:04 UTC
Hi everyone

I'm new on this git, but I just wanted to share my idea and see your reactions.

So, what if we created/used a chrome/Firefox extension that downloads and seeds torrent files over the bittorrent and webtorrent network. This way we can close the gap between these networks. And make a 100% browser side torrent client.

From a user's perspective:
- goes to website
- wants to download torrent/play video
- a) torrent file is available on webtorrent network
  -> starts direct download
  -> seeds to webtorrent network
- b) torrent file is not available on webtorrent
  -> is asked to install extension
  -> starts to download
  -> seeds to webtorrent network (&bittorrent)

**Comment by aqwsez** [comment] 2015-09-27 11:03
Does anyone think this is a good idea, is realistic and/or has any value to this project?

**Comment by Stiveknx** [comment] 2015-09-28 17:44
I think it is an great ideia!
It would help a lot!

Altought I think we would need some ideias to share the extensions to another users, I mean, why they would change from their current clients to another one?

Also, two another good ideias I've to solve the gap:
A desktop client (can be built with nw.js).
A tool to download files on a seedbox / dedicated server (from udp peers), and share it with webtorrent clients.

This second ideia, I started a project a few months ago, and it's working fine, for my tests.

**Comment by devTristan** [comment] 2015-09-28 18:28
https://github.com/feross/chrome-net relevant?

**Comment by iadj** [comment] 2015-09-30 23:45
+1 for this idea!

**Comment by ericwooley** [comment] 2015-10-01 00:25
We made a working chrome extension for webtorrent for a hackathon, it worked pretty well https://github.com/RosettaLabs/Torrentula (webRTC only). Something changed with the chrome api and local storage and it doesn't run anymore, should be a fairly easy fix though if you guys want to fork it or canabalize it. It has a fully functional add/delete/view torrent manager built in react with a flux architecture.

**Comment by devTristan** [comment] 2015-10-01 13:56
That's interesting. I think the great thing about using a chrome app for this, though, would be access to the primary bittorrent network.

**Comment by aqwsez** [comment] 2015-10-01 16:03
Thank you for the comments, I'm currently trying to figure out how exactly everything is working.
I think we first should start creating a hybrid client (if this doesn't exist yet).
After that we can try to implement this in a chrome extension.

My current questions:
- is there already a hybrid client?
- are webtorrent and bittorrent torrent files/ magnet links useable for both (if not how do we link them)?
- how do clients find each other?
- where/how are the torrent files getting stored?

Also I found this project:
https://github.com/mafintosh/torrent-stream
This project is very simular to this project but uses bittorrent, if there is no hybrid client yet we can use this project to create one.

**Comment by ericwooley** [comment] 2015-10-01 16:30
> is ther a difference between webtorrent and bittorrent torrent files/ magnet links (if this is the case how do we link them)?

No, there is no difference, the issue is that webtorrent (in browser) is limited to webRTC, and other clients haven't implemented that connection method

> how do clients find each other?
There are two methods of finding peers, a tracker, or a DHT (Distributed Hash Table). You can lookup how either work

> where/how are the torrent files getting stored?
I am still not exactly sure about how it is stored in browser. It might be in memory if you download it. This is used, https://github.com/mafintosh/memory-chunk-store but I don't think it does local storage or anything.

**Comment by gillesdemey** [comment] 2015-10-01 20:09
Check out https://github.com/feross/webtorrent-hybrid for a bridge between BitTorrent/BitTorrent over WebRTC.

**Comment by devTristan** [comment] 2015-10-01 20:20
webtorrent-hybrid is just webtorrent with a native wtrc module. Since chrome apps can already do wrtc, I think just `net` needs to be polyfilled, which is why I posted https://github.com/feross/chrome-net. It says it's used by webtorrent, but it isn't. This makes me think that @feross tried to get webtorrent to work in a chrome app recently.

I think building webtorrent with browserify, substituting chrome-net for net, might work. Somebody should try it.

**Comment by ericwooley** [comment] 2015-10-01 20:30
@devTristan I think you are mistaken about webtorrent-hybrid, it connects to both webrtc and TCP/UDP peers. Webtorrent (non-hybrid) is only for webrtc in the browser, and IIRC only tcp/udp in node.

So you need to use webtorrent hybrid for both. Webtorrent will only do one, or the other, depending on the enviornment.

**Comment by devTristan** [comment] 2015-10-01 20:33
Right, sorry, that's what I meant. See the source code:

https://github.com/feross/webtorrent-hybrid/blob/master/index.js
https://github.com/feross/webtorrent-hybrid/blob/master/lib/global.js

**Comment by devTristan** [comment] 2015-10-01 20:37
Looks like `net` availability is determined here at least, possibly elsewhere... https://github.com/feross/bittorrent-swarm/blob/master/index.js#L320

**Comment by DiegoRBaquero** [comment] 2015-10-26 04:25
Great idea! +1

**Comment by jimmywarting** [comment] 2015-11-11 00:29
+1 
Its definitely doable! Just tried [torrent stream](https://chrome.google.com/webstore/detail/torrent-stream/icocmgpofpimcojhefbcfbdldkmndpgj?utm_source=chrome-ntp-icon) chrome extension 

It uses bittorrent in a chrome extension. It can stream torrents and its also seekable witch is grate! (think the CPU went up when i tried)

**Comment by devTristan** [comment] 2015-11-11 15:20
I managed to get this working a while ago. It's an MVP but it runs.

https://gist.github.com/devTristan/b768d2ee571350d5b796

The hard part was aliasing all of the node-only modules and overriding browser excludes. It was pretty easy to find chrome-compatible modules to polyfill things like `net` and `dgram`, because @feross already made them! I was also able to grab `native-dns` to polyfill `dns`. That just uses the `net` module provided by `chrome-net` and gets DNS resolving using the chrome APIs.

What works:

 - Downloading and seeding on the bittorrent network
 - Downloading and seeding on the webtorrent network (it's a hybrid client!)
 - The DHT. My favorite data structure. Thanks, `chrome-dgram`!
 - Downloading totally legal torrents and embedding them in video tags. Thanks, blender open movie project!

What doesn't work:

 - Anything after about 3 minutes. It crashes either the app or the entire browser. Pretty neat, huh?

I don't know why it crashes. I suspect it's something to do with trying to allocate too much in the way of resources - memory, disk space, network connections, etc. When I do profiling, it looks like the JS-Native bridge is the bottleneck with all of the network api calls, but I could be wrong.

You should be able to clone my gist and try it out yourself. Happy hacking.

**Comment by loon3** [comment] 2015-11-13 03:01
I'm having the same issue with everything working fine for a couple minutes, but I can actually watch the CPU utilization slowly tick up as well as the Packets in/out.  My guess is it's slowly duplicating processes but I can't figure out why.  This is my background script... https://github.com/loon3/Tokenly-Pockets/blob/master/Chrome%20Extension/js/webtorrent/bvam-seed.js

**Comment by eliooses** [comment] 2015-11-13 08:40
Hi @devTristan !, 

I try to run your extension, but i can makes work.

I put the bundle.js (not include in your package at same of app.css) and the code retrieve the follows erros:

Failed to load resource: net::ERR_FILE_NOT_FOUND
3extensions::platformApp:17 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.(anonymous function) @ extensions::platformApp:17
2extensions::platformApp:17 window.toolbar is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
2extensions::platformApp:17 window.statusbar is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
2extensions::platformApp:17 window.scrollbars is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
2extensions::platformApp:17 window.personalbar is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
2extensions::platformApp:17 window.menubar is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
2extensions::platformApp:17 window.locationbar is not available in packaged apps.

**Comment by devTristan** [comment] 2015-11-13 14:06
Hey @eliooses, did you use the `npm run watch` or `npm run watch-js` script to kick off your build?

I think all of those warnings are fine, but the `net::ERR_FILE_NOT_FOUND` error might be related to the aliasing of the `fs` module as `base:/fakefs.js`. Make sure `fakefs.js` is in the same directory as your `package.json`.

**Comment by elad** [comment] 2015-12-04 08:47
This idea - torrent client as a Chrome extension - was actually one of the first things I did when starting to play with webtorrent. It was very easy to get working. If anyone's interested in the code, I can upload everything I have as-is to a repository.

**Comment by aqwsez** [comment] 2015-12-04 10:55
Hey, I created this https://github.com/aqwsez/webtorrent_chrome repo can you upload it? Thanks

**Comment by professorhaseeb** [comment] 2015-12-04 13:25
@aqwsez blank repo!!!

**Comment by thisisritz** [comment] 2016-10-24 20:32
Is anyone still working on something here? I would like to contribute. Would be awesome to be able to download regular torrents from the browser and seed them on webtorrent

**Comment by knoopx** [comment] 2017-02-02 08:23
FYI:  
> Important: Chrome will be removing support for Chrome Apps on Windows, Mac, and Linux. Chrome OS will continue to support Chrome Apps. Additionally, Chrome and the Web Store will continue to support extensions on all platforms. Read the announcement and learn more about migrating your app.

https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by HughIsaacs2** [comment] 2017-05-04 03:24
To bring this back alive, something I'd like to add.

Building support for the Chrome UDP Sockets API in WebTorrent should also allow us to build WebTorrent support in Android apps via Google's sockets.udp Cordova plugin [https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp) and even though Google is dropping support for Chrome Apps on Windows, Mac and Linux, I'd argue that Chrome OS support is still important considering that the userbase on that end keeps growing.

**Comment by devmattrick** [comment] 2018-01-08 02:36
I'm a bit late to the party here, but it would be nice to have the extension also give sites using the WebTorrent API the ability to use the raw sockets provided by browser extensions (it seems to currently only be [supported by Chrome](https://developer.chrome.com/apps/sockets_tcp), but there is a [proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1247628) to add it to the WebExtensions spec). This would allow WebTorrent clients to be able to access the entirety of the BitTorrent network without clients supporting WebRTC needing to be available.

I'm not entirely sure how the client <-> extension communication would work, but I imagine there are a number of ways of going about it. One possible way is to somewhat replicate how the [Vue DevTools](https://github.com/vuejs/vue-devtools/blob/master/src/backend/hook.js) extensions does it; it adds a property to the window which is essentially an EventEmitter bridge between the extension and client script.

**Comment by feross** [comment] 2018-05-09 02:13
FWIW, I think a WebTorrent Chrome App is a great idea for Chrome OS users. I think that it won't help Mac, Windows, and Linux users much since Chrome Apps are deprecated and support will eventually be removed.

Unfortunately, the `chrome.sockets` API is only available in Chrome Apps not Chrome Extensions, so we can't make a Chrome Extension that allows full torrent network connectivity including over TCP and UDP.

For that reason, I personally don't consider making a Chrome App to be a top priority but if someone wants to take a stab at making one, go for it.

**Closed by feross** 2018-05-09 02:13 UTC
Labels: wontfix
