### ISSUE TITLE
Number of Seeders/Leechers

### ISSUE THREAD

**Issue by GuacheSuede** [webtorrent/webtorrent#459] opened 2015-10-10 04:58 UTC
Hello Webtorrent,

how does one get total number of peers(seeders, leechers) without downloading ?

Cheers

**Comment by gillesdemey** [comment] 2015-10-13 15:58
You can do this by "scraping" a tracker, see https://wiki.vuze.com/w/Scrape.

You can use https://github.com/feross/bittorrent-tracker as a client (see https://github.com/feross/bittorrent-tracker#client).

**Comment by GuacheSuede** [comment] 2015-10-14 18:03
Hi Gillesdemy,

what about DHT and PEX, ?

I believe there are DHT, PEX and trackers ? correct me if i am wrong

Cheers

**Comment by gillesdemey** [comment] 2015-10-14 18:19
There's a project that harvests IP addresses of peers https://github.com/Stefan-Code/peer-harvest that uses PEX and DHT.

DHT works very differently from regular trackers, there's a great presentation on crawling the DHT: https://www.defcon.org/images/defcon-18/dc-18-presentations/Wolchok/DEFCON-18-Wolchok-Crawling-Bittorrent-DHTS.pdf

For PEX, you can listen for new peers and keep track of a unique map of connected peers to the swarm.
See https://github.com/Stefan-Code/peer-harvest/blob/master/peer-harvest.js#L305-L324

**Comment by GuacheSuede** [comment] 2015-10-14 18:28
Ah neat, Thank you for the links. 

El Psy Congroo

**Comment by rom1504** [comment] 2016-01-07 19:08
duplicate of https://github.com/feross/webtorrent/issues/298

**Closed** 2018-05-04 00:59 UTC
