### ISSUE TITLE
Seeding files above about 100MB on smartphone Chrome causes crash

### ISSUE THREAD

**Issue by tom-adsfund** [webtorrent/webtorrent#2221] opened 2021-11-14 01:45 UTC
Using a basic but fast smartphone (Moto G8), Chrome crashes trying to seed a 170MB file. It works with a 70MB file, but I guess if the hashing continues too long, the page crashes.

When the file isn't immediately seeded in full, the file loads properly with no issue.

**Comment by tom-adsfund** [comment] 2021-11-14 23:20
Being able to control the rate of seed hashing will be essential if there's more files to seed at the same time.

I'm thinking that there could be a heuristic so that if the hashing is happening slower than a certain rate you could introduce 10ms(?) pauses to make sure nothing becomes unresponsive.

**Comment by ThaUnknown** [comment] 2021-11-15 09:38
what chunk store did you use?
what version did you use?
what browser did you use?
what browser version did you use?
for the future. the default issue template is there for a reason

**Comment by tom-adsfund** [comment] 2021-11-15 12:30
WT 1.5.6, Android Chrome 95.0.4638.74
Whatever the default chunk store is.

**Comment by ThaUnknown** [comment] 2021-11-15 13:18
> WT 1.5.6, Android Chrome 95.0.4638.74 Whatever the default chunk store is.

my bad, I should have been more specific, I expected you to answer the questions in the default template, and the questions I provided were just generic "you didn't give enough information".

what android version is it, how much RAM does your phone have, how do you seed the files, what crash error is it, steps to reproduce.

I cannot reproduce this issue on my Redmi note8 or on PC with a 20GB file, so you must be doing something wrong?

**Comment by tom-adsfund** [comment] 2021-11-15 13:52
Trying to max out seeding (try seeding a 300MB file from a HTML file chooser) on your Redmi Note 8 would probably be a good test to show this affects Android Chrome smartphones generally.

But thinking about it more, I'm not sure even if you could change WT to seed a 200MB file on a low-end smartphone it would be a great idea, because ultimately the maximum memory for the tab will be reached with large files. And if multiple files are seeded exhausting the memory will definitely happen.

So I would give you more info on the phone I'm using but I'm not really sure that's going to be useful given what I've just said.

**Comment by ThaUnknown** [comment] 2021-11-15 14:35
you still didn't provide steps to reproduce this, again, this works just fine on my phone from a file picker with a 20 GB file, so you must be doing something wrong

**Comment by tom-adsfund** [comment] 2021-11-15 15:03
Sorry, I didn't read that sentence properly!!

But on my desktop, I use this code with a 177MB video file, and get the following result:

```
console.log(file.name +":"+ Date.now());
wt.seed(file, {announce: ["wss://my-tracker..."]}, (torrent)=>{
  console.log(file.name +":"+ Date.now());
});

6955452955136240.mp4:1636988328273
6955452955136240.mp4:1636988340881
= 12608ms = 12 seconds
```

**Comment by ThaUnknown** [comment] 2021-11-15 15:11
okay... but how do you reproduce the issue? you just showed some code from the docs and said "this works", again, I can't in any way reproduce this issue

**Comment by tom-adsfund** [comment] 2021-11-15 16:05
Just from my perspective, I can't see a solution to this because basically some hash function will have to process the file, and on a desktop it's taking 12 seconds, and so together with the memory requirements, I'm just going to leave it.

I can only guess that when you checked, it was just firing off the seed function without timing when the torrent is ready?

Anyway, I think I'm going to leave this.

**Comment by ThaUnknown** [comment] 2021-11-15 16:42
I still don't understand the issue, the sha1 doesn't leak any RAM, nor does it persist any RAM usage across the hashing of different pieces, it might in some extreme cases be too quick for V8 to GC, but I've only had that happen on 2-way raid0 with 2 NVME M.2's, but your phone will never match those speeds, and the only RAM spike you will see is from the cache chunk store, which in the long run helps a lot. I will assume that you used memory store, which cauched a RAM exceeded error, which afaik is 1.4GB on mobile, and close this

**Closed** 2021-11-15 16:43 UTC

**Comment by tom-adsfund** [comment] 2021-11-15 16:50
The RAM issue is just a broader problem that isn't directly affecting this problem. I'm just forecasting forward on whether it's worth pursuing solving this problem only to face another one.

I'm not sure what's causing this crash, but I just assume it's some kind of Chrome process kill that happens automatically if there is too much CPU activity for too long... but to be honest I have no idea.
