### ISSUE TITLE
WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by viet1pro** [webtorrent/webtorrent#1674] opened 2019-07-21 17:04 UTC
I also have this error with `tracker.btorrent.xyz` although i can visit their website with no problem.

**Comment by SilentBot1** [comment] 2019-07-21 17:20
Hi @viet1pro 

The `tracker.btorrent.xyz` tracker which powers the [BTorrent.xyz](https://btorrent.xyz/) website is ran by @DiegoRBaquero and isn't part of the main WebTorrent library even though it's one of the default trackers. 

The repository for the [BTorrent](https://btorrent.xyz/) website can be found [here](https://github.com/DiegoRBaquero/BTorrent/) and it appears that there is already an issue reporting an ongoing fault with the tracker which can be found [here](https://github.com/DiegoRBaquero/BTorrent/issues/69).

As this issue doesn't relate to the WebTorrent library, I'm going to close this. I would recommend reinforcing and adding to the already existing issue over in the [BTorrent issue tracker](https://github.com/DiegoRBaquero/BTorrent/issues/) to let @DiegoRBaquero know the issue is still ongoing. 

Kind regards
Brad

**Closed by SilentBot1** 2019-07-21 17:20 UTC
