### ISSUE TITLE
There is no button to control the seed and the download speed !

### ISSUE THREAD

**Issue by aniani01** [webtorrent/webtorrent#1755] opened 2019-10-08 18:43 UTC
**What version of this package are you using?** 0.21.0 (0.107.16)

**What problem do you want to solve?** No control over the speed !

**What do you think is the correct solution to this problem?** Adding buttons to control the upload and download speed options, just like utorrent !

**Are you willing to submit a pull request to implement this change?** Yes

**Comment by alxhotel** [comment] 2019-10-08 20:34
Duplicate of [webtorrent-desktop#435](https://github.com/webtorrent/webtorrent-desktop/issues/435)

**Closed** 2020-09-19 06:51 UTC
Labels: wontfix
