### ISSUE TITLE
Port is requested

### ISSUE THREAD

**Issue by adam-wadsworth** [webtorrent/webtorrent#1822] opened 2020-03-25 09:02 UTC
I'm currently developing a torrent stream app using Electron and WebTorrent.

When running WebTorrent within Electron I'm getting the following error:

Uncaught Error: Option `port` is required

I've noticed several people have left similar issues, but haven't had any response.

Please could you let me know how to resolve this issue, if its not a WebTorrent problem, please let me know.

Thank you.

**Comment by iffa** [comment] 2020-04-11 20:30
```typescript
  // any port in this range
  clientPort = Math.random() * (60000 - 12000) + 12000;
  client = new WebTorrent({
    // @ts-ignore missing from typedef
    torrentPort: this.clientPort,
  });
```

pass torrentPort when creating the client. port can literally be whatever

**Comment by alxhotel** [comment] 2020-07-10 22:59
Duplicate of #1783

**Closed by alxhotel** 2020-07-10 22:59 UTC
