### ISSUE TITLE
Can not add the same torrent again after adding and destroying it 

### ISSUE THREAD

**Issue by yujiahaol68** [webtorrent/webtorrent#1195] opened 2017-09-27 04:35 UTC
**What version of WebTorrent?**
0.98.19

**What operating system and Node.js version?**
darwin, node 8.4

**What browser and version? (if using WebTorrent in the browser)**
electron 1.7.5

**What did you expect to happen?**
After I use `torrent.destroy` and `client.add` use the same `torrentId` and `path` again. It can resume the previous download task.

**What actually happened?**
`client.add` works in the first time but the second time failed after I have `torrent.destroy` it
Not any error have been throw and also not any download signal or speed.

**Comment by feross** [comment] 2018-05-04 00:36
Duplicate of https://github.com/webtorrent/webtorrent/issues/1180

**Closed by feross** 2018-05-04 00:36 UTC
