### ISSUE TITLE
Transfer is seriously strangled while browser tab is in background

### ISSUE THREAD

**Issue by jimmywarting** [webtorrent/webtorrent#1568] opened 2019-01-11 16:52 UTC
**What operating system and Node.js version?**
Dosen't affect Node

**What version of WebTorrent?**
0.103.x

**What browser and version? (if using WebTorrent in the browser)**
Chrome v72

**What did you expect to happen?**
Expected `process.nextTick` to not use `setTimeout`

**What actually happened?**
The problem is with `process` browserified version of `process.nextTick` it uses a `setTimeout(fn, 0)` as a fallback. The `setTimeout` is delayed well enough in foreground to strangle the speed from 6-7000 kb/s down to just 400 kb/s when one tab is hidden "to save resources". if you instead use two windows the speed will be fast (normal) again.

> `setTimeout(fn, 0)` can potentially be used, however as it is clamped to 4ms for timers nested more than 5 deep per the HTML spec, it does not make for a suitable [polyfill](https://github.com/YuzuJS/setImmediate) for the natural immediacy of setImmediate. - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate)

Downloading from hybrid torrents works fine cuz they uses node nextTick version.
So to test this you basically need to upload some large files to [instant.io](https://instant.io/) and open up the sharable instant.io link in a new tab or new window

This affect users who want to download something and watch cat videos while its uploading/downloading

**Comment by RangerMauve** [comment] 2019-01-11 18:15
What would be a better alternative to process.nextTick? It might be possible to detect the browser environment and reassign it to something better or do a PR against browserify.

**Comment by jimmywarting** [comment] 2019-01-11 21:07
> What would be a better alternative to process.nextTick?

If possible don't use nextTick at all in both `memory-chunk-store` and `immediate-chunk-store` and possible other places where it's not needed? not sure if streams uses nextTick also.

To me it looks like: 
- PeerA request a piece from PeerB
- PeerB calls `store.get()`
- store calls memory `store.get()`
- memory `store.get` waits 4ms and then return it to immediate store
- immediate waits 4ms and then gives that to bittorent-protocol

now you waisted 8ms or more. Both storage layer don't use the same eventLoop when nextTicket is called in both of them it's more like a chain reaction then a parallel execution

It seems to me that this is also almost all pointless b/c of `process.nextTick()` turns into `setTimeout(fn, 0)`
https://github.com/webtorrent/webtorrent/blob/5b7c5eebf41c9e1e1fe8e9e1d4a6ad06e93e7430/lib/torrent.js#L46-L47

IndexedDB chunk stores will be wrapped in immediate-chunk-store so when you create a Buffer or Blob it will exit the current eventLoop and exit the current transaction?

**Comment by RangerMauve** [comment] 2019-01-11 21:13
As I understand the use of `nextTick` is important in order to make sure all callbacks that are supposed to be invoked asynchronously, are guaranteed to be invoked asynchronously. This helps make async code more consistent and helps avoid race conditions in async code.

Maybe browserify should use this [setImmediate](https://github.com/YuzuJS/setImmediate) polyfill instead of `nextTick`?

**Comment by RangerMauve** [comment] 2019-01-11 21:20
The code would need to be changed [in the module that Browserify uses for `process`](https://github.com/defunctzombie/node-process/blob/master/browser.js#L38).

I think that `Promise.resolve().then(cb).catch((e) => setTimeout(()=> throw e,0))` might be closer to what `nextTick` is supposed to do than `setImmediate` or `setTimeout`

**Comment by RangerMauve** [comment] 2019-01-11 21:53
I think this is more of an issue for Browserify to update their `nextTick` implementation, and I'm sure they'd welcome a PR or might have some issues already discussing this.

**Comment by calvinmetcalf** [comment] 2019-01-11 22:53
so the default process.nextTick does indeed use setTimeout, but only in situation of process.nextTick being called the first time, for recursive calls to process.nextTick it'll be called as soon as the process.nextTick queue is empty.

You'll note that we had discussed using things besides setTimeout, but the reason it was vetod for 2 reasons, the first is because the process module gets included in a LOT of code so any bloat on our end would be passed into a staggering number of down stream codebases which is something we wanted to avoid.  The second and more subtle reason is that this code get's run in a dizzying array of environments (and if you don't believe me look at the issues related to caching setTimeout) so we would have to deal with a lot of very strange corner cases that could break code even for some users that don't even use process.nextTick.

That being said you could always check out my library [immediate](https://github.com/calvinmetcalf/immediate) which is literally just process.nextTick but also using mutation observers and message channels and whatnot it's probably exactly what you want if the default one is not quite doing it for you.

**Comment by feross** [comment] 2019-08-24 00:18
We need `process.nextTick` for consistent async behavior. Read https://blog.izs.me/2013/08/designing-apis-for-asynchrony for more information.

@jimmywarting What do you think about swapping all uses of `process.nextTick` with [`immediate`](https://github.com/calvinmetcalf/immediate) to resolve this issue?

**Comment by jimmywarting** [comment] 2019-08-24 19:20
> We need process.nextTick for consistent async behavior. Read https://blog.izs.me/2013/08/designing-apis-for-asynchrony for more information.

Isaac has a point that a callback should always be either async or sync for consistent behavior. but i would not follow he's rule so strictly, if you don't need it to be consistent and you can handle both scenarios then why bother using next tick or immediate at all? In my fork i just removed it, seems to work just fine.

I would follow that rule more strictly if it is a one time thing but if it is something that is repeatable and slows down performance under lots of load then i would thing twice before using it. especially when it will be executed in the background.

One reason for not using a next cycle would be b/c of the indexed-db layer.
if you can insert/read stuff in a same transaction everything would just work much faster to store seeded files and export everything when you want to save something.

**Comment by feross** [comment] 2019-09-07 18:51
>  if you don't need it to be consistent and you can handle both scenarios then why bother using next tick or immediate at all? In my fork i just removed it, seems to work just fine.

It's about making the API work correctly even when the user of it doesn't code defensively. It prevents really nasty tricky bugs when the user assumes that the function will always be called asynchronously.

**Comment by feross** [comment] 2019-09-07 18:51
I assume this issue title was meant to say "background" not "foreground", right? I updated the title.

**Comment by feross** [comment] 2019-09-07 20:32
The solution that I'd like to propose here is to switch all `process.nextTick` calls across the codebase to `queueMicrotask`. This is a new API analogous to Node's `process.nextTick` but it works in the browser environment too.

I published a package to make it easier to use: https://github.com/feross/queue-microtask

**Comment by feross** [comment] 2019-09-07 21:28
If folks would like to start sending PRs to replace usage, I've sent a few to `simple-peer` and `simple-websocket` already, which you can use as examples:

- https://github.com/feross/simple-peer/pull/543
- https://github.com/feross/simple-websocket/pull/59

**Comment by KayleePop** [comment] 2019-09-11 21:16
Here's a PR for immediate-chunk-store https://github.com/feross/immediate-chunk-store/pull/9

BTW, this problem goes away when async functions are used instead of callbacks

**Comment by feross** [comment] 2019-09-11 23:37
@KayleePop Thanks for the PR :)

> @KayleePop BTW, this problem goes away when async functions are used instead of callbacks

Yep. I'd love to switch to a promise-based API at some point :)

**Comment by ftreesmilo** [comment] 2020-08-06 03:19
What to do about the torrent.js use of CHOKE_TIMEOUT as a delay?

**Comment by feross** [comment] 2020-11-23 21:45
> What to do about the torrent.js use of CHOKE_TIMEOUT as a delay?

I don't believe this is related to this issue. The choke timeout is part of the normal functioning of the torrent protocol. This issue is about unnecessary slow downs caused by the browser throttling `setTimeout` calls when a tab is in the background.

**Comment by feross** [comment] 2020-11-23 21:50
I'd like to resume working on this issue to improve WebTorrent performance. We should replace all `process.nextTick` calls with [`queueMicrotask`](https://www.npmjs.com/package/queue-microtask) across all WebTorrent packages.

Who wants to help send PRs to do this?

**Comment by S0llarCode** [comment] 2022-09-09 16:03
@ThaUnknown

Indeed, it's the same problem. I don't find any process.nextTick in the webtorrent code. They all seem to have been replaced by queueMicrotask.

But the problem persists.
You can find this tab problem in version 1.8.29 #2370 

When I compile webtorrent.min.js, I find process.nextTick in these dependencies.

**Closed** 2023-01-23 16:45 UTC
Labels: enhancement, help wanted, area/browser, good first contribution, area/perf, accepted
