### ISSUE TITLE
.mkv play

### ISSUE THREAD

**Issue by AceVance** [webtorrent/webtorrent#1107] opened 2017-04-19 23:41 UTC
Can't seem to play/stream .mkv files. Would be HUGE help! Thanks!

**Comment by AceVance** [comment] 2017-04-19 23:42
Thanks in advance!!!

**Comment by marcus-sa** [comment] 2017-04-19 23:45
Browser or desktop?
The <video> tag doesn't support .mkv playback, as for desktop you'd have to use an external player as VLC.

**Comment by AceVance** [comment] 2017-04-19 23:51
no no no, browser. Imagine the possibilities. Can I contact you in private?

**Comment by kocoten1992** [comment] 2017-04-20 03:03
@AceVance , mkv is the container, the codec in container are factor video can play it or not (like h.264, vp9...).

But in my exp, sometimes even codec are vp9 (supported by firefox/chrome) and with mkv container, firefox won't play it, chrome however can. It best to stick with container surely browser support (mp4 / webm...)

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by AceVance** [comment] 2017-04-20 04:03
The trick is to stream mkv from a torrent file through web app, without anything downloaded to an actual computer, except the cache. Which is possible. Just need to figure out the right way of getting mkv presented to the player in a way where it will understand the video/audio formats. That's the ultimate goal.

**Comment by AceVance** [comment] 2017-04-20 04:04
and again, thank you very much Kocoten1992 and marcus-sa for all the input. Can't thank you enough for engaging in this.

**Comment by kocoten1992** [comment] 2017-04-20 04:52
It too confused, could you elaborate in much detail ?
```js
// and please don't open a thread with a single sentence
```

**Comment by Daniel-Abrecht** [comment] 2017-04-20 06:45
Isn't this a duplicate of #405, #796 and https://github.com/jhiesey/videostream/issues/29 again?

**Comment by DiegoRBaquero** [comment] 2017-04-20 20:58
Duplicate.

**Closed by DiegoRBaquero** 2017-04-20 20:58 UTC
