### ISSUE TITLE
Is WebTorrent Desktop Ever gonna get updated or is it Dead ?

### ISSUE THREAD

**Issue by Kristijan1001** [webtorrent/webtorrent#2498] opened 2023-03-12 19:56 UTC
This has been updated constantly, but the Webtorrent Desktop App is still like 3 years old.

**Comment by DubiousTunic** [comment] 2023-03-22 22:52
Yes and I would add that torrents don't seed to browser after running for ~3 minutes making it essentially defunct!!

**Comment by vankasteelj** [comment] 2023-04-28 22:11
Webtorrent moving to ESM (from CJS) and Webtorrent-desktop being built on Electron, itself being not compatible with ESM (as far as I know, at least), I'm afraid there's an incompatibility issue here: the app could be updated, but not with the latest webtorrent patches and fixes.

**Comment by ThaUnknown** [comment] 2023-05-07 09:15
duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/2272

**Closed by ThaUnknown** 2023-05-07 09:15 UTC
