### ISSUE TITLE
Can't change External media player in Mac OS Catalina

### ISSUE THREAD

**Issue by NIXOYE** [webtorrent/webtorrent#1746] opened 2019-09-16 20:25 UTC
**What version of this package are you using?**
0.21.0
**What operating system, Node.js, and npm version?**
Mac OS Catalina
**What happened?**
Can't change the external media player
**What did you expect to happen?**
expected to be able to change the external media player
**Are you willing to submit a pull request to fix this bug?**
sure?

**Comment by feross** [comment] 2019-09-16 22:31
Thanks for filing an issue. Can you be a bit more detailed? What exactly happens when you click the button to change the external media player -- does it just do nothing?

Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by NIXOYE** [comment] 2019-09-17 18:13
Yeah it just doesn't do anything.

`/Applications/WebTorrent.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:17 Uncaught Error: Could not call remote method 'showOpenDialog'. Check that the method signature is correct. Underlying error: Default path must be a string
Underlying stack: TypeError: Default path must be a string
    at openDialog (/Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/api/dialog.js:89:15)
    at Object.showOpenDialog (/Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/api/dialog.js:145:16)
    at Object.showOpenDialog (/Applications/WebTorrent.app/Contents/Resources/electron.asar/common/api/deprecate.js:144:32)
    at /Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/rpc-server.js:370:67
    at EventEmitter.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)

    at /Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/rpc-server.js:373:21
    at EventEmitter.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)`

**Comment by feross** [comment] 2019-09-18 00:40
Thanks for that stack trace. That will be very helpful. This indeed looks like a bug.

**Comment by hicom150** [comment] 2019-09-18 18:48
Could be related to https://github.com/webtorrent/webtorrent-desktop/pull/1702

**Comment by feross** [comment] 2019-09-18 18:53
Yep, this appears to be a duplicate of that issue.

**Comment by artemmolotov** [comment] 2020-05-03 15:09
Same problem on Windows 10 1909 (18363). 
I can't change external media player.

Do I need to create a new issue or not?

WebTorrent Desktop v0.21.0

```log
Uncaught Error: Could not call remote method 'showOpenDialog'. Check that the method signature is correct. Underlying error: Default path must be a string
Underlying stack: TypeError: Default path must be a string
    at openDialog (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\api\dialog.js:89:15)
    at Object.showOpenDialog (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\api\dialog.js:145:16)
    at Object.showOpenDialog (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\common\api\deprecate.js:144:32)
    at C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\rpc-server.js:370:67
    at EventEmitter.<anonymous> (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\api\web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)

    at C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\rpc-server.js:373:21
    at EventEmitter.<anonymous> (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (C:\Users\AnEasy\AppData\Local\WebTorrent\app-0.21.0\resources\electron.asar\browser\api\web-contents.js:342:29)
    at WebContents.emit (events.js:200:13)
```

**Comment by hicom150** [comment] 2020-09-21 19:33
Should be already fixed in the last version of [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.24.0) 😉

**Closed by hicom150** 2020-09-21 19:33 UTC
Labels: bug, help wanted, needs reproduction
