### ISSUE TITLE
some data from the filelist cannot enter client.seed ()

### ISSUE THREAD

**Issue by zombiesg** [webtorrent/webtorrent#1894] opened 2020-07-23 13:43 UTC
**What version of this package are you using?**
using webtorrent v0.108.6
**What operating system, Node.js, and npm version?**
using
-windows 10 build 19041
-firefox 78.0.2 and chrome 84.0.4147.89
-nodejs v12.18.2
-yarn 1.22.4
-vue framework @vue/cli@4.4.6
**What happened?**
some data will bring up "premature close", when client.seed (). and data like exe and dll,will be error. I have 2 "ico" files. but one of them ("app.ico") will issue "premature close"
![Capture](https://user-images.githubusercontent.com/68360996/88293166-d4be9d00-cd24-11ea-88a0-42f7004a587c.PNG)
[file ico.zip](https://github.com/webtorrent/webtorrent/files/4966254/file.ico.zip)
**What did you expect to happen?**
i want no error
**Code**
```
let client = new WebTorrent()
let files=document.getElementById("file-input").files;
client.seed(files, function (torrent) {
     console.log('Client is seeding ' + torrent.infoHash)
})
```
**Are you willing to submit a pull request to fix this bug?**
because I'm a beginner, it seems like I won't do it

**Comment by alxhotel** [comment] 2020-09-21 14:39
Duplicate of #1757

**Closed by alxhotel** 2020-09-21 14:39 UTC
Labels: wontfix
