### ISSUE TITLE
Uncaught Error: Can only pipe to one destination

### ISSUE THREAD

**Issue by Igol4** [webtorrent/webtorrent#2522] opened 2023-04-14 12:54 UTC
**What version of this package are you using?**
2.0.16

**What operating system, Node.js, and npm version?**
OS: Win11
Node.js: v18.16.0
npm: 9.5.1

**What happened?**
got this error trying to run example website (https://webtorrent.io/intro#:~:text=%3C!doctype%20html%3E%0A%3Chtml%3E%0A%20%20%3Cbody,script%3E%0A%20%20%3C/body%3E%0A%3C/html%3E)

Uncaught Error: Can only pipe to one destination
    at ReadableState.pipe (webtorrent.min.js:16:173759)
    at module.exports.pipe (webtorrent.min.js:16:179641)
    at webtorrent.min.js:16:216698
    at Array.forEach (<anonymous>)
    at MP4Remuxer.seek (webtorrent.min.js:16:216602)
    at VideoStream._pump (webtorrent.min.js:16:220728)
    at VideoStream.VideoStream._onWaiting (webtorrent.min.js:16:219710)

**What did you expect to happen?**
I expected it to stream the video.
**Are you willing to submit a pull request to fix this bug?**
Unfortunately, no, I'm just starting to learn development and I don't know how to fix complex codes.

I also get errors 
webtorrent.min.js:16     GET https://webtorrent.io/torrents/Sintel/Sintel.mp4 net::ERR_CACHE_OPERATION_NOT_SUPPORTED
Client

and

WebSocket connection to 'wss://tracker.fastcast.nz/' failed: 

Sorry if I did something wrong and if this is not a bug, but I can't find any resource online on how to fix this.

**Comment by rishabhjainfinal** [comment] 2023-04-20 00:55
same error !!!

**Comment by Igol4** [comment] 2023-04-22 23:05
user on stackoverflow suggested adding this version of the scriot instead of the latest one :

https://cdn.jsdelivr.net/npm/webtorrent@1.8.0/webtorrent.min.js

and it worked. Although in the meantime i gave up using webtorrent because it does not support widely used trackers like udp so i cannot feed it with magnet from 1337x or thepiratebay

**Comment by ThaUnknown** [comment] 2023-04-23 11:18
duplicate of https://github.com/webtorrent/webtorrent/issues/2369

**Closed by ThaUnknown** 2023-04-23 11:18 UTC
