### ISSUE TITLE
speed-limiter does not work as expected.

### ISSUE THREAD

**Issue by YOUPERT-INC** [webtorrent/webtorrent#2210] opened 2021-10-26 17:28 UTC
**What version of this package are you using?** version 1.5.7

**What operating system, Node.js, and npm version?** Windows 10 Pro x64, Node.js 16.13.0, npm 8.1.1 

**What happened?** I pulled version 1.5.7 in order to utilize the downloadLimit and uploadLimit param in the Webtorrent constructor and set downloadLimit : 20MB/s and uploadLimit : 20MB/s. But download speed exceeded way beyond 40MB/s when I downloaded a file with lots of peers.

**What did you expect to happen?** I expected download speed would be capped at 20MB/s

**Are you willing to submit a pull request to fix this bug?** Not sure as I don't know about how exactly speed-limiter works.

**Comment by DiegoRBaquero** [comment] 2022-01-06 12:25
@alxhotel we are limiting the real bytes, but the protocol and wrapper also uses BW. As in, the encrypted webrtc with extra protocol messages is using more bw, thoughts?

**Comment by devqazi** [comment] 2022-01-06 12:31
@DiegoRBaquero  There is an interesting related issue, Sometimes the torrent speed starts accumulating and reaches unrealistic numbers exceeding1GB/s (yes!, capital B) which is of course erroneous. Though this might just be a rare and incredibly hard to reproduce underlying bitterant protocol implementation bug, because I have encountered the same issue (though only once) with  q-bit-torrent and twice with u-torrent. 

So the problem might not even be with "speed reporting" part of the code.

**Comment by ThaUnknown** [comment] 2022-01-06 13:40
> @DiegoRBaquero There is an interesting related issue, Sometimes the torrent speed starts accumulating and reaches unrealistic numbers exceeding1GB/s (yes!, capital B) which is of course erroneous. Though this might just be a rare and incredibly hard to reproduce underlying bitterant protocol implementation bug, because I have encountered the same issue (though only once) with q-bit-torrent and twice with u-torrent.
> 
> So the problem might not even be with "speed reporting" part of the code.

if you are using WT's speed reporting then this is probably likely the cause of inaccurate speed reporting: https://github.com/webtorrent/webtorrent/issues/2226

**Comment by ThaUnknown** [comment] 2022-11-12 22:18
it has been half a year, unless someone can reproduce this [outside of webtorrent desktop which is insanely outdated] I'm gonna close this soon

**Closed** 2023-01-27 15:54 UTC
Labels: bug, accepted, needs reproduction
