### ISSUE TITLE
Why is WebTorrent using all my memory on my iMac all 32gig

### ISSUE THREAD

**Issue by BlockLists** [webtorrent/webtorrent#1637] opened 2019-06-04 11:38 UTC
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by BlockLists** [comment] 2019-06-04 11:39
Why is WebTorrent Using all my memory on my iMac ? all 32 gigs of it?

**Comment by jimmywarting** [comment] 2019-06-04 12:25
I would have close this issue for 4 reasons

- you didn't fill in the issue template
- you didn't describe what you did that caused the memory to fill up
- you basically didn't put in any effort in to writing a decent issue, the comment is the same as the title.
Think of a meaningful title, don't write the hole issue in the title. or vise versa.
- Have you tried debugging exactly where all the memory goes to? (using chrome memory devtools) we don't know exactly what you did that caused the memory to fill up. and how to reproduce the problem. Was it due to a lot of peers? many files? many torrents? was it WebRTC or just regular peers? node or browser?
- did you use any chunk storage to save all data? otherwise all data is stored in the memory

Good example: 

## Webtorrent is using a lot memory.

I have a iMac with 32GB ram and when added 50 torrent files (14 of which is paused) WebTorrent 0.103.2 uses all available memory and then later chrome crashes.

All 50 torrents sums up to roughly 120 gb in total. And i'm connected to roughly 500 WebRTC peers.

**Comment by jimmywarting** [comment] 2019-06-04 12:26
Don't be lazy!

**Comment by BlockLists** [comment] 2019-06-04 21:20
Its a memory leek. Debug it yourself it’s not hard and then fix it, don’t
be lazy.

**Comment by jimmywarting** [comment] 2019-06-04 21:55
> it’s not hard and then fix it

So why don't you make a PR then?

**Closed** 2019-06-04 21:57 UTC
