### ISSUE TITLE
Implement Protocol Encryption (PE/MSE)

### ISSUE THREAD

**Issue by transitive-bullshit** [webtorrent/webtorrent#69] opened 2014-05-29 20:30 UTC
Protocol encryption (PE) aka message stream encryption (MSE) is a bittorrent extension to enhance privacy and confidentiality, effectively making bittorrent traffic harder to identify and throttle by ISPs.

Note that there is no official BEP describing protocol encryption, but it is widely supported by all the top clients.

At a high level, there are two different levels of bittorrent encryption that exist, namely those which only encrypt bittorent headers, and stronger encryption such as RC4 which encrypts the entire stream.  I'm guessing that webtorrent will want to eventually support both, but I'd recommend implementing the header-level encryption first since webtorrent is already heavily burdened by all the SHA1 hashes going on.

bittorrent-clients should accept encryption options similar to those described [here](http://www.bittorrent.com/intl/fr/help/manual/appendixa0206); e.g., encrypted connections should be either disabled, enabled and optional (e.g. prefer encryption but fallback to unencrypted if the remote peer doesn't support encryption), or enabled and forced (e.g., only connect to peers supporting encryption).

Resources:
- [Bittorrent protocol encryption](http://en.wikipedia.org/wiki/BitTorrent_protocol_encryption) on Wikipedia
- Sourceforge article on [MSE](http://sourceforge.net/apps/mediawiki/spid/index.php?title=Identifying_the_Message_Stream_Encryption_%28MSE%29_protocol)
- [MSE in Vuze](http://wiki.vuze.com/w/Message_Stream_Encryption)

**Comment by NumDeP** [comment] 2018-05-23 13:29
Hi @feross 

When I initially came across this issue and wanted to continue using the product as I liked it's functionality compared to others (not to mention the partnership with Brave), I wanted very briefly discuss with you something I had in mind with a freelance cryptographer surrounding the encryption feature and propose whether you like Tribler or Joystream and perhaps contemplate juxtaposing the solution/s because torrent clients such as Bitcomet and Deluge are good services but don't receive the support they deserve and there way too many client available which unlike Webtorrent are feature heavy and I thought it would have been an excellent way to support Webtorret in the end.

 I'm sorry to say that my earlier comment wasn't meant to be jaded at all :(

**Comment by feross** [comment] 2018-05-25 08:00
@NumDeP Thanks for explaining, no worries. It's hard to read tone of voice over text. I'm sorry for assuming your tone was rude. No hard feelings ❤️

**Comment by NumDeP** [comment] 2018-05-25 21:42
Don't be silly, no need to apologies. In reference to my last comment, I know it's not the right place to discuss this and you must be hammered with to-do's and pulling hemingways like there's no tomorrow but it would be quite nice if Webtorrent-Brave and Webtorrent-Desktop users similarly like the aforementioned solutions were to support Webtorrent in similar means.

**Comment by heri16** [comment] 2019-04-29 21:26
Any reason why the PRs have not been merged?

**Comment by fijiwebdesign** [comment] 2019-04-30 00:04
> I don't think ISPs will be throttling WebRTC any time soon.

UAE blocks WebRTC to control the Voip. I think encryption will *NOT* mitigate it since I vaguely remember peers not able to establish connections. This went on and off in the few years I was there. 

I can't remember but there was 1 other country I had the same issue. It would be nice if a reproducible test could be put in place either using proxies? or tested by users on different ISPs? 

> This is important for webtorrent.app, but less important for webtorrent.js since WebRTC already automatically encrypts data streams.

Would be beneficial since there are a lot more countries monitoring/filtering/throttling BitTorrent traffic.

**Comment by jimmywarting** [comment] 2019-04-30 10:38
> UAE blocks WebRTC

That's stupid. Nobody should be allowed to control the internet. Damm those who go against net neutrality.

**Comment by NumDeP** [comment] 2019-07-10 14:30
Shadowsocks is a feature in this service https://mullvad.net/en/guides/intro-shadowsocks/ I wonder if it would it be possible to implement into webtorrent when it becomes obvious that the software, either standalone or in Brave-Browser isn't working due to ISP or nation states. 

In addition, @figiwebdesign why didn't you just utilise a VPN to mitigate this yourself?

Here's the open source link to the feature - https://github.com/mullvad/shadowsocks-rust

**Comment by fijiwebdesign** [comment] 2019-07-11 04:51
> In addition, @figiwebdesign why didn't you just utilise a VPN to mitigate this yourself?

@NumDeP Sure, but isn't really a solution for everyone. Baking something into WebTorrent is much better. 

Note: 

VPNs are banned in some countries - https://thebestvpn.com/are-vpns-legal-banned-countries/

For UAE specifically here is an extract: 

> A punishment of temporary imprisonment and a fine of not less than AED 500,000 and not more than AED 2,000,000, or either of these two penalties, shall be imposed on whoever uses a fraudulent computer network protocol address by using a false address or a third-party address or by any other means for the purpose of committing a crime or preventing its discovery.

**Comment by ultimate-tester** [comment] 2020-02-29 10:33
> 
> 
> > In addition, @figiwebdesign why didn't you just utilise a VPN to mitigate this yourself?
> 
> @NumDeP Sure, but isn't really a solution for everyone. Baking something into WebTorrent is much better.

I don't agree, WebTorrent has 1 function which is to download and upload torrents according to the BitTorrent protocol. Any fiddling with network traffic does not belong to WebTorrent but the operating system's network configuration. 

Encrypting the protocol according to PE/MSE though, IS a responsibility of WebTorrent since it's regarding the implementation of the protocol. Therefore I'd like to get the attention back to this pull request over here https://github.com/webtorrent/bittorrent-protocol/pull/36

**Comment by ivan1986** [comment] 2020-03-14 02:16
update https://github.com/webtorrent/bittorrent-protocol/pull/36 to master https://github.com/webtorrent/bittorrent-protocol/pull/48

**Comment by ivan1986** [comment] 2020-03-15 21:38
#1820

**Comment by ivan1986** [comment] 2020-03-15 21:40
tested - all works fine

**Comment by ivan1986** [comment] 2020-03-20 22:45
@ultimate-tester @feross @transitive-bullshit ping
its work and tested, need update protocol repository and after that update this repository

**Comment by ivan1986** [comment] 2020-04-14 12:00
@ultimate-tester @feross @transitive-bullshit ping
what also need to integrate support?
very want to see this feature - many torrent clients use force encription

**Comment by ultimate-tester** [comment] 2020-05-05 16:03
Hi @ivan1986  perhaps I missed something but I believe the PR is still open right? Once it goes through I can have a look what needs to be done. Not sure if anything though, the BitTorrent library should be able to handle both encrypted and I encrypted connections from that moment and webtorrent will benefit from it.

**Comment by ivan1986** [comment] 2020-05-05 16:55
@ultimate-tester yes, it's still open. After update to master i test webtorrent with popcorn time and pair with deluge with 3 different value of option encrypt - all works fine.
For full merge need merge PR in bittorent-protocol repo, update version in package.json and merge this pr.

**Comment by ivan1986** [comment] 2020-05-12 23:13
#1820 rebased
Any reason why the PRs have not been merged?

**Comment by ivan1986** [comment] 2020-08-06 03:08
@ultimate-tester @feross @transitive-bullshit ping

**Comment by ivan1986** [comment] 2020-09-01 17:15
@feross 
Why havn't any progress? All tested and works fine.
Need only merge webtorrent/bittorrent-protocol#48 update version and merge #1820

**Comment by ivan1986** [comment] 2020-10-22 20:08
@ultimate-tester @feross @transitive-bullshit ping

**Comment by ivan1986** [comment] 2020-10-28 01:10
@feross pls look on this PR - without this lose many clients with forse enrypted

**Comment by ivan1986** [comment] 2021-02-24 19:48
@feross ping
pls merge this two requests

**Comment by ivan1986** [comment] 2021-03-27 16:38
tested on popcorn time ru fork - all looks good, download from secure and not-secure sources fine, some torrents very inc peers

**Comment by ivan1986** [comment] 2021-04-27 18:55
Many torrents get performance issue - in PR it's disabled, in fork i add option in webtorrent

**Closed** 2021-10-04 20:56 UTC
Labels: enhancement, help wanted, area/browser, area/node, accepted

**Comment by ThaUnknown** [comment] 2026-01-27 08:41
this is broken, and has been since release, incoming connections work but outgoing don't, I tried fixing it a bit and improved it, but the original implementation had stuff like `while (true) {}` in it's code, which is a massive no-go in JS land, I'm unsure how it was ever approved/reviewed
