### ISSUE TITLE
BEP6 breaking webtorrent with certain torrent clients

### ISSUE THREAD

**Issue by ivan1986** [webtorrent/webtorrent#2258] opened 2022-01-31 13:33 UTC
[webtorrent/bittorrent-protocol/commit/319136d7146135abfb25deade4ae5693d309e79f](https://github.com/webtorrent/bittorrent-protocol/commit/319136d7146135abfb25deade4ae5693d309e79f)

**What version of this package are you using?**
update from 1.5.8 to 1.7.2

**What operating system, Node.js, and npm version?**
linux, windows
nwjs 0.44.5

**What happened?**
after update everything stops responding i get cpu usage 25-75% (never got that high before) and memory usage just keeps increasing forever

**Comment by ThaUnknown** [comment] 2022-04-06 18:56
this is caused by some rouge torrent clients out there, and leads some sort of infinite loop which just creates new objects without GC'ing them and making the node process unresponsive, effectively causing massive RAM and CPU leaks

debugging what client causes that however is difficult, pretty much the only way to find out is to test against all versions of all torrent clients out there, it could even be webtorrent causing it

**Comment by ThaUnknown** [comment] 2022-04-20 13:17
@paullouisageneau from what [limited] testing I've done, it seems to be caused when connecting to other non-webtorrent peers, as I can't reproduce this issue on WebTorrent:WebTorrent peers, any idea what in the BEP implementation could be causing this?

**Comment by paullouisageneau** [comment] 2022-04-20 13:26
@ThaUnknown I'll look into it.

**Comment by paullouisageneau** [comment] 2022-04-20 14:41
I found the potential infinte loop issue, could you please test if the fix  https://github.com/webtorrent/bittorrent-protocol/pull/88 prevents the issue?

**Comment by ThaUnknown** [comment] 2022-04-22 12:11
its possible this was fixed with https://github.com/webtorrent/bittorrent-protocol/pull/79 but since reproducing this issue is uuuuuh... painful to say the least, I'm struggling to reproduce it, the last version i know it happened on was WT v1.8.1

**Comment by ThaUnknown** [comment] 2022-04-24 00:07
just so I don't leave anyone hanging:
from what I can tell this issue seems fixed, I'll leave it open till the end of the week, but mass testing showed no issues with this anymore, but again, since we don't know what client was causing this, I can't say with certainty this is fixed, but it's probably safe to assume it should be fine for production

**Comment by ThaUnknown** [comment] 2022-04-28 15:05
fixed as of 1.8.14

**Closed by ThaUnknown** 2022-04-28 15:05 UTC
Labels: help wanted, bug, area/perf, accepted, released
